apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  name: aws-iam-authenticator
  labels:
    app: vcluster
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  config.yaml: |
    # a unique-per-cluster identifier to prevent replay attacks
    # (good choices are a random token or a domain name that will be unique to your cluster)
    clusterID: vcluster-oidc
    server:
    #   hostname: aws-iam-authenticator-svc.v-cli-18c99kitar-3sta-oidc.svc.cluster.local
    #   port: 21362

      mapRoles:
      - roleARN: arn:aws:iam::520011374273:role/xttapan-man-k-intcorp-euie-01-vclu-oidc-kubeadmin
        username: kubernetes-admin
        groups:
        # - system:master
        - system:basic-user